### ISSUE TITLE
I couldn't choose the source and control in samsung Q70R

### ISSUE THREAD

**Issue by tieppm** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#1]
I am using sony 55x8500G TV and Q70r soundbar
I have followed your instructions and succeeded.
But I couldn't choose the source and I cannot control anything
Can you solve this problem?

```Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/smartthings_soundbar/api.py:38
First occurred: 21:17:48 (317 occurrences)
Last logged: 22:15:08

Update for media_player.ss_q70r fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 77, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 38, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

![Untitled](https://user-images.githubusercontent.com/42457105/78265961-56e54480-752f-11ea-827c-a961b7a0917d.png)

**Comment by PiotrMachowski** [comment]
Are you sure your config is correct?

**Comment by tieppm** [comment]
@PiotrMachowski 
my congifg
![1](https://user-images.githubusercontent.com/42457105/78376271-46e56780-75f8-11ea-8757-5f6ddefba3ed.png)

**Comment by tieppm** [comment]
thank you very much. 
I just checked it again and found out it was wrong at Device ID
I have corrected and succeeded.

**Comment by PiotrMachowski** [comment]
That's great :)
By the way, does `samsung_multi_room` work with your soundbar?

**Comment by tieppm** [comment]
@PiotrMachowski 
samsung_multi_room  not work :(
you can send media from hass to sounbar with WIFI?

**Comment by PiotrMachowski** [comment]
Unfortunately I am not able to do it :(
Right now I have Chromecast Audio connected to it, so I send media to Chromecast

**Comment by tieppm** [comment]
you conect chromecast to soundbar and send media from hass to chromecast?
Hope to have a solution soon

**Comment by PiotrMachowski** [comment]
Exactly

**Comment by tieppm** [comment]
Hi.
1. I do not understand what this slider is for? Can it be used to control volume like the Google home mini?
2. I do not see the HDMI ARC source

**Comment by PiotrMachowski** [comment]
1. Yes, that's volume slider
2. There is no separate HDMI ARC source, there is a common one for optical input and HDMI ARC. It is called `digital` (at least in my case)

**Comment by tieppm** [comment]
The left volume bar is worth 0? The right is worth 100?

**Comment by PiotrMachowski** [comment]
Yes

**Comment by tieppm** [comment]
I update your component and it very good
Thank U
You can update worth in volume slide
EX
![IMG_20200404_100551](https://user-images.githubusercontent.com/42457105/78417434-3070f780-765c-11ea-9ea9-334b2e1fe6f7.jpg)

**Comment by PiotrMachowski** [comment]
In current version you can scale volume in HA so that 100% in HA will match a desired volume on the soundbar (eg. 30%). I find it very useful as it gets laud very fast.

**Comment by tieppm** [comment]
@PiotrMachowski 
Thank U :D
