### ISSUE TITLE
Q70T support

### ISSUE THREAD

**Issue by peetereczek** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#10]
Hi,

I just launched your integration with Samsung Q70T Soundbar and it seems fine, more less. I can see the states, controle volume, select source, turn on/off

I wonder what are the states of the integration, why idle while playing from Wi-Fi?
![image](https://user-images.githubusercontent.com/42431204/111127943-a7a15200-8574-11eb-926e-1ade74a227ff.png)

And source was digital instead of Wi-Fi
![image](https://user-images.githubusercontent.com/42431204/111128072-cef81f00-8574-11eb-8d3b-7b1733199215.png)
as I played music over Spotify Connect (which is Wi-Fi from soundbar perspective). It doesn't pull current source from device, despite it can control it correctly.

**Comment by PiotrMachowski** [comment]
Can you check the state of your device [here](https://graph-eu01-euwest1.api.smartthings.com/device/list)?

**Comment by peetereczek** [comment]
In SmartThinks soundbar is online:

![image](https://user-images.githubusercontent.com/42431204/111590223-1f19f000-87c6-11eb-8629-ab34e7ac05ca.png)

But in HA is inactive:

![image](https://user-images.githubusercontent.com/42431204/111590298-39ec6480-87c6-11eb-8ebf-4241b7e1cb6d.png)

**Comment by PiotrMachowski** [comment]
Inactive in my implementation means that it is turned on in mode that doesn't support media control (HDMI/Toslink). It is set to playing/paused/stopped in modes that support media control (WiFi/BT). Can you check it out?

**Comment by peetereczek** [comment]
That's right. While I was playing music from Spotify, there were playing/paused/stopped statuses

![image](https://user-images.githubusercontent.com/42431204/112155150-4f59f800-8be5-11eb-9402-fcc255735991.png)

**Comment by PiotrMachowski** [comment]
Fixed in v1.0.2
