### ISSUE TITLE
Ability to change sound modes

### ISSUE THREAD

**Issue by PrMinisterGR** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#14]
Hello, thank you for your work!

I own an HW-Q950T, and I would love to have the ability to change between sound modes on the bar (Standard, Surround, Adaptive etc). Since this can be changed via the SmartThings API, I suspect there might also be a way to do this via this integration.

Is this possible?

**Comment by PiotrMachowski** [comment]
Have you found this functionality in SmartThings API? It wasn't there last time I was looking for it

**Comment by PrMinisterGR** [comment]
Apologies, I misunderstood something I saw.

**Comment by PiotrMachowski** [comment]
This feature is only available for Samsung TVs
https://developer-preview.smartthings.com/docs/devices/capabilities/capabilities-reference
