### ISSUE TITLE
HW-N950 SUPPORT_PLAY_MEDIA?

### ISSUE THREAD

**Issue by masterpae** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#15]
Hello, thank you very much for your work. I was able to install and use your integration perfectly on my HW-N950.

Looking at the supported features for my soundbar entity (19853) it seems there is no support for SUPPORT_PLAY_MEDIA.
Is it possible to have this feature added to this integration?

Can we in any way have media_player.play_media be usable with Samsung soundbars?

**Comment by PiotrMachowski** [comment]
It is not possible via SmartThings, maybe it's possible using DLNA
