### ISSUE TITLE
Home Kit 

### ISSUE THREAD

**Issue by niko0303** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#18]
I can Control my HW-Q800A without Problems in Home Assistant  but when I add it to Home Kit i am not able to change Volume or the Source I just get a group of 4 Buttons to Turn On/OFF, Mute, Play-Pause, Play-Stop is there any way to Control the Soundbar from Homekit like a TV?

**Comment by PiotrMachowski** [comment]
I have no idea, I do not use Home Kit. Is it possible to control other media players from it?
