### ISSUE TITLE
More options for hw-q900a

### ISSUE THREAD

**Issue by Bastiencc** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#19]
Hi

The integration works well for my q900a, very nice job, thanks !

In the smarthing apps, there are some others options, like : 
- sound mode 
- subwoofer level
- auto EQ
- night mode
- etc...

is it possible to add them on the integration ?

thanks !

**Comment by PiotrMachowski** [comment]
They are not listed in SmartThings API, so I don't think it's possible

**Comment by Bastiencc** [comment]
Hello ,
Just to check, still not possible?

**Comment by PiotrMachowski** [comment]
No changes here. You can monitor API functionalities [right here](https://developer-preview.smartthings.com/docs/devices/capabilities/capabilities-reference/)
