### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by BlaRock86** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#2]
When I add the 3 files in the correct folder, and use tmy API and ID key, I get the following:

"Platform error media_player.smartthings_soundbar - Integration 'smartthings_soundbar' not found."

**Comment by PiotrMachowski** [comment]
Have you restarted HA? Is there anything more in logs (right after restart of HA)?

You can add this repo as a custom repository in HACS, it will download everything for you https://hacs.xyz/docs/faq/custom_repositories

**Comment by BlaRock86** [comment]
Hi, After adding the repo through Hacs, the errors were gone. No idea how that fixed it. (folder and files were the same)
(restarted dozens of time :P )

But still didn't see it appearing, so I made a new token, and that seemed to solve the problem.

All works good now. Thx for the quick reply. (still new to all this HA-stuff)
