### ISSUE TITLE
media_player not found

### ISSUE THREAD

**Issue by silversmarty** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#20]
Hello,

thanks for this awesome component!
When I launch a spotify playlist on the media_player.soundbar entity that has been created, an error is given :

<img width="426" alt="image" src="https://user-images.githubusercontent.com/17980711/146671055-b26a07de-b112-4557-beb5-7f3ebfb7ccaf.png">

Is there anything to do to fix this?
(my soundbar is a HW-S61T)

Thanks again!

**Comment by silversmarty** [comment]
I've finally succeed in launching the playlist, by using the spotify device id and not the entity_id.
The procedure is explained here : https://www.reddit.com/r/homeassistant/comments/ni1gw1/psa_for_using_home_assistant_to_force_your/

**Comment by PiotrMachowski** [comment]
Fixed in v1.0.2
