### ISSUE TITLE
New Supported Devices

### ISSUE THREAD

**Issue by BrendanxP** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#24]
I am not sure if this is the right channel to convey this information, but I wanted to let you know that your code works great on my device which is not yet on the supported devices list.

HW-S61T (2020)
HW-S60T (2020)

![image](https://user-images.githubusercontent.com/25636915/151706595-7e61e713-9573-4340-8886-fdce81dc8765.png)

**Comment by PiotrMachowski** [comment]
Thanks!
