### ISSUE TITLE
Unable to add as an Integration

### ISSUE THREAD

**Issue by Snips1** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#28]
Have installed custom repository via HACS but am unable to add as an integration..

please help!

**Comment by PiotrMachowski** [comment]
You have to add it using yaml

**Comment by Snips1** [comment]
How would I go about doing that?

Ive tried the manual installation but I cant get the to work either

**Comment by PiotrMachowski** [comment]
If you have added it to custom repositories in HACS then you just have to search for "soundbar" in "integrations" section of HACS and install it. Then you have to add configuration to configuration.yaml and restart HA

**Comment by Snips1** [comment]
Thats where im having trouble.

I have added it to custom repositories in HACS - Restarted
Then when I search for Soundbar in HACS, nothing shows?

**Comment by PiotrMachowski** [comment]
You can get it by clicking on it in the list of custom repos

**Comment by Snips1** [comment]
Its right there on the HACS tab, but not joy adding as an integration.. I just will not show!

**Comment by PiotrMachowski** [comment]
I'm not sure what you mean... Have you installed it and now you have problems with configuration, or do you have problems with installation?

**Comment by Snips1** [comment]
These are the steps ive taken:
1. Installed custom repo via HACS
2. Selected the SmartThings Soundbar in HACS & installed the repository (install button at the bottom)
3. Edited configuration.yaml with relevant info
4. Restart HA

Cant get anything working from there - Appreciate you taking the time to respond btw. Im a bit of a noob at this!

**Comment by PiotrMachowski** [comment]
Ok, it looks fine for me. It should appear on entities list in dev tools. Is it there?

**Comment by Snips1** [comment]
Its there twice as:

**media_player.soundbar**
volume_level: 1
is_volume_muted: false
media_title: 
source: 
device_class: speaker
friendly_name: Soundbar
supported_features: 19853

&

**update.smartthings_soundbar_update**
auto_update: false
installed_version: v1.0.2
in_progress: false
latest_version: v1.0.2
release_summary: null
release_url: https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/releases/v1.0.2
skipped_version: null
title: null
entity_picture: https://brands.home-assistant.io/_/smartthings_soundbar/icon.png
friendly_name: Soundbar
supported_features: 17

**Comment by PiotrMachowski** [comment]
Soooo it's installed and configured.

**Comment by Snips1** [comment]
Ok so you getting me to look into Dev Tools finally made it click!

Its working prefectly. I was looking for a UI in Integrations and then figured out just to create a button on the dashboard.

Thanks so much for your help! Just to confirm, its working perfectly on the Q950a 👍
