### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by LiquidBlackNL** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#29]
Seems like te work with the HW-Q990B (2022).
Which is not yet on the supported devices list. :)

![image](https://user-images.githubusercontent.com/50137101/176547376-57f9b3d9-aa3d-43b8-b102-33ce2899bf93.png)

Thx!

**Comment by PiotrMachowski** [comment]
@LiquidBlackNL Thank you! Device added 👍 
Woah, Samsung has finally added Chromecast 😮
