### ISSUE TITLE
Feature Request; Change sound mode

### ISSUE THREAD

**Issue by patroza** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#30]
HW-Q990/995/950A/T, the ability to change the sound mode (Standard, Surround, Game, Adaptive)

**Comment by PiotrMachowski** [comment]
It's not possible using SmartThings API
https://developer-preview.smartthings.com/docs/devices/capabilities/capabilities-reference

Duplicate of #14
