### ISSUE TITLE
Changing "MediaPlayer to "TV"

### ISSUE THREAD

**Issue by joeblack2k** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#31]
Hey,

i'm trying to change my device_class to tv because imo it makes more sense for HomeKit usage
- ability to change volume
- ability to change channels (HDMI1,2) 

but when i try to change the device_class in hassio i get into a iceberg of "This entity does not have a unique ID"

so now i'm stuck..

is there a way to change the device_class or give it a unique ID ?

thanks for reading!

**Comment by PiotrMachowski** [comment]
You can do it in `configuration.yaml`: https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities
