### ISSUE TITLE
Samsung HW-Q70T

### ISSUE THREAD

**Issue by robkarpati** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#34]
Hi, 
Can you please add Samsung HW-Q70T support to this integration?
Thanks a lot.

**Comment by PiotrMachowski** [comment]
Have you checked if it works with current version?

**Comment by robkarpati** [comment]
Yes I did, but it did't for me.
But if I think well it is nearly the same as Samsung HW-Q70R.

**Comment by robkarpati** [comment]
If I try to play a radio station I get this but with Spotify playlist it is the same:
Failed to call service script/media_play_tilos_radio. Entity media_player.soundbar does not support this service.

**Comment by robkarpati** [comment]
Maybe it doesnt support "play by url"?
But I (we) dont have any idea why it doesnt work.

**Comment by PiotrMachowski** [comment]
No, SmartThings doesn't support it

**Comment by robkarpati** [comment]
Oh, so it is because of smartthings?
Than sorry for bothering you.

**Comment by PiotrMachowski** [comment]
Ok, so does everything else work?

**Comment by robkarpati** [comment]
Yes, thank you very much, 
so we can close the topic.
