### ISSUE TITLE
High delay when changing volume 950Q soundbar

### ISSUE THREAD

**Issue by Ontrackx** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#36]
When changing volume with slider there is a long delay before actually changing the volume on soundbar.
This makes the user think the volume slider is not working.

**Comment by PiotrMachowski** [comment]
It seems more like a problem on side of your network connection - commands are sent to soundbar via the Internet

**Comment by PiotrMachowski** [comment]
@Ontrackx Spotify app controls the soundbar directly over the local network using Spotify Connect protocol
