### ISSUE TITLE
select source via node red?

### ISSUE THREAD

**Issue by simondib** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#38]
How could I set the source via a node red flow? Using `select_source` gives me an api error.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/7483506/210774927-d799c23f-aaeb-4e10-9191-52206d12eec1.png">

**Comment by PiotrMachowski** [comment]
It works with `media_player.select_source` just like any other media_player. You can try it in HA directly
