### ISSUE TITLE
Feature Request; choose the audio sync

### ISSUE THREAD

**Issue by jax93300** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#39]
Hi,

First of all big thanks to you for this integration.

As you probably know, we are facing of a big issue on the Q990B with plex when we want to play a movie @ 24p, we have a big audio desynchronized, it's around 280-300ms. In the smart thing app we can choose to adjust the audio sync between 0 and 300 ms.

I wanted to know if you can add this features in that way I can choose the audio sync in nodered when I turn on the shield I'll put 300 ms in audio sync, and when I turn on the PS5 I'll choose 0 ms.

Big thanks by advance,

Cheers,

**Comment by PiotrMachowski** [comment]
Unfortunately there's no such feature in SmartThings API
https://developer.smartthings.com/docs/devices/capabilities/capabilities-reference
