### ISSUE TITLE
Hub Requirement ?

### ISSUE THREAD

**Issue by dn4hc** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#41]
Thanks for the plugin, do I need a smart things hub to add my soundbar?

I have Samsung HW-Q950T and Q950A and trying to add to home assistant to control without launching the slow app on phone every time.

Can this work without the hub and if yes, I can't find soundbar in [Device List] [Create Device][type] dropdown?

Any help will be appriciated.

**Comment by PiotrMachowski** [comment]
Yes, it should work without the hub.

Do you have a list of devices displayed when you go to [this](https://graph-eu01-euwest1.api.smartthings.com/device/list) link?

example:
![image](https://user-images.githubusercontent.com/6118709/218704426-91149536-98aa-4298-91c1-9d71109ecea4.png)

**Comment by dn4hc** [comment]
No I don’t see it. Using the same Samsung account. 


Home:

![101A9F5F-C22D-4F83-9DBD-345D4DF80194](https://user-images.githubusercontent.com/3523129/218706203-5e7794bf-0a98-47e6-8220-01887bd60f30.png)
![DAEE7442-BE76-4F2E-9BC7-C3BEDD322230](https://user-images.githubusercontent.com/3523129/218706235-28f44d0e-6c52-4c01-9099-b77b3f6db1f7.png)


Devices:
![F5AFB3E0-77F8-4374-8BD0-97BFC371B43C](https://user-images.githubusercontent.com/3523129/218706341-bfa8805a-9205-4a2c-8e7a-df5dc4b241c5.png)
![B45A7128-2F91-4C73-8EC6-13CE871F904F](https://user-images.githubusercontent.com/3523129/218706358-4883f5c4-05b0-49c6-8072-4330a5bfd33c.png)

**Comment by PiotrMachowski** [comment]
Do you have any soundbar-related device added to HA when you add SmartThings integration?

**Comment by dn4hc** [comment]
Deleting and readding seems to have fixed it,.

**Comment by PiotrMachowski** [comment]
Great 👍
