### ISSUE TITLE
Any chance of LOCAL control?

### ISSUE THREAD

**Issue by zhdenny** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#43]
SmartThings API kinda sucks. Is there any chance we can get Local control of our Soundbars instead of relying on outside services (SmartThings)?

**Comment by PiotrMachowski** [comment]
Well, this integration is dedicated just for SmartThings API, so I don't plan to hack around to get local control

**Comment by zhdenny** [comment]
Anyone know any project who has figured out Local Control?
