### ISSUE TITLE
W sumie to nie issue

### ISSUE THREAD

**Issue by Woszu1981** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#47]
Witaj,
Nie zgłaszam problemu. ale nie bardzo wiem jak inaczej napisać.
Mam pytanie - czy można wykorzystać soundbar jako media player w HA? 
Mam tą integracje, ale jest tylko sterowanie, 
Jak odtworzyć coś w HA na głośniku?

**Comment by PiotrMachowski** [comment]
Nie widziałem takiej możliwości w API Smarttgings
