### ISSUE TITLE
Media_player Not a Unique ID

### ISSUE THREAD

**Issue by PimStevens** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#49]
Hi,
Thanks for developing this great integration! I hope you are able to help me.
I have a Samsung HW-Q990B installed and running the SmartThings app and integration. I installed successfully your component using HACS. For the Soundbar I still can only see status and turn on/off.  I have booted HA after install in HACS and after config and the media_player do show up among the entities. 
My configuration looks like this:
# Samsung Soundbar Q990B
media_player:
  - platform: smartthings_soundbar
    name: Soundbar_HS
    api_key: "c3dee59f-a373-445f-92e4-xxxxxxxxxxxxx"
    device_id: "b86f12fa-9473-9350-4f4d-xxxxxxxxxxxxx"
    max_volume: 30
But I only see the On/Off switch on the device page.
 
When I go to the entity, I see the media_player.soundbar_HS.
  
But when I click on the entity and the config wheel, I get the message: This entity ('media_player.soundbar_hs') does not have a unique ID, therefore its settings cannot be managed from the UI.
 
Do you have any idea to solve this? I’m rather new in HA, so I don’t know what to do.

Best Regards,
Pim

**Comment by PiotrMachowski** [comment]
Soundbar won't show up on "Integrations" page, it is only available as an entity.

Missing unique id doesn't restrict usability of the media_player entity

**Comment by PiotrMachowski** [comment]
yes, it's normal. I would have to implement it
