### ISSUE TITLE
Installing via HACS

### ISSUE THREAD

**Issue by fbutler** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#53]
Hi,

The README says "After adding a custom repository you can use HACS to install this integration using user interface"

However when I try installing using the user interface within HACS I get the message: "This device cannot be added from the UI You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."

Fergal

**Comment by PiotrMachowski** [comment]
Yes, you can *install* it using HACS interface, but to *configure* it you have to use `configuration.yaml` file

**Comment by fbutler** [comment]
OK, thanks. 

 

I’m new to Home Assistant and with other custom integrations that I’ve installed I’ve been used to carrying out the configuration via the UI as well. 

 

As the README didn’t mention further configuration was required in the HACS section, I assumed that this behaviour was an issue.

 

Thanks for your prompt response.

 

Fergal

**Comment by PiotrMachowski** [comment]
Hopefully soon this integration won't be necessary: https://github.com/home-assistant/core/pull/95692
