### ISSUE TITLE
Used API discontinued and shutdown

### ISSUE THREAD

**Issue by Utty88** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#54]
Since last saturday I can't get anymore status updates by the HA-custom-component.

The used API-URL just returns a 503 error: https://graph-eu01-euwest1.api.smartthings.com/

In the SmartThings community there is a community thread that this API has been discontinued: https://community.smartthings.com/t/is-the-ide-web-page-down/274174
Is it possible to refactor this component to the new API?

**Comment by zsmb13** [comment]
Seems like the integration itself still works fine, at least my Soundbar can still be controlled by it.

The README links however which use the `https://graph-eu01-euwest1.api.smartthings.com/` URLs don't work though, which made it difficult to find my device ID.

I ended up finding this link to use instead, which lists your devices if you're authenticated, including the necessary `deviceId`: https://api.smartthings.com/v1/devices

The README should probably be updated to include this link now.
