### ISSUE TITLE
Samsung N950 not playing media (mp3 or TTS)

### ISSUE THREAD

**Issue by Andurilll** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#56]
It does not play any file sent. I tried media or TTS
How would i configure this correctly?

I get this Error:
Logger: homeassistant.components.dlna_dmr
Source: components/dlna_dmr/media_player.py:76
Integration: DLNA Digital Media Renderer (documentation, issues)
First occurred: 15:18:50 (3 occurrences)
Last logged: 15:19:01

Error during call async_play_media: UpnpActionResponseError('Error during async_call(), action: SetAVTransportURI, status: 500, upnp error: 716 (Resource not found)')

**Comment by Andurilll** [comment]
this is the automation content:
```
service: media_player.play_media
target:
  entity_id: media_player.av_av_samsung_soundbar_n950
data:
  media_content_id: media-source://media_source/local/Willow short version.mp3
  media_content_type: audio/mpeg
metadata:
  title: Willow short version.mp3
  thumbnail: null
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://media_source
enabled: true
``

**Comment by PiotrMachowski** [comment]
This entity is not provided by this integration

**Comment by PiotrMachowski** [comment]
Exactly :)
