### ISSUE TITLE
Can you document the needed scopes from SmartThings token?

### ISSUE THREAD

**Issue by thllxb** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#59]
Hi,
I'm just started configuring this plug-in. When I was creating the token from SmartThings, there was a big list of scopes I need to choose from, but I'm not sure which one is needed to let your plug-in work. I can take a guess to try-and-fail a few times, but it would be nice if it is documented.
Thank you.
Here is the list of scope I got:

- [ ] Devices
  - [ ] List all devices
  - [ ] See all devices
  - [ ] Manage all devices
  - [ ] Control all devices

- [ ] Installed Applications
  - [ ] List all installed apps
  - [ ] See all installed apps
  - [ ] Manage all installed apps

- [ ] Scenes
  - [ ] List all scenes
  - [ ] See all scenes
  - [ ] Control this scene

- [ ] Applications
  - [ ] See all apps
  - [ ] Manage all apps

- [ ] Channels
  - [ ] Read all channels
  - [ ] Manage all channels

- [ ] Custom Capabilites
  - [ ] Read custom one or all capabilities
  - [ ] Write one or all custom capabilities

- [ ] Device Profiles
  - [ ] See all device profiles
  - [ ] Manage all device profiles

- [ ] Drivers
  - [ ] Read all drivers
  - [ ] Manage all drivers

- [ ] Invitations
  - [ ] Read all invitations
  - [ ] Manage all invitations

- [ ] Locations
  - [ ] See all locations
  - [ ] Manage all locations
  - [ ] Control all locations

- [ ] Rules
  - [ ] See all rules
  - [ ] Manage all rules
  - [ ] Control this rule

- [ ] Schedules
  - [ ] See all schedules
  - [ ] Manage all schedules

- [ ] Notifications
  - [ ] Control all notifications

- [ ] Audio/Video
  - [ ] Record a clip
  - [ ] List clips
  - [ ] Capture an image
  - [ ] List images
  - [ ] Start a live stream
  - [ ] List live streams

**Comment by PiotrMachowski** [comment]
https://www.home-assistant.io/integrations/smartthings/#personal-access-token-pat
