### ISSUE TITLE
N950 - not working properly

### ISSUE THREAD

**Issue by aherbjornsen** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#6]
I just installed this and there seems to be some problems controlling my N950.

I cannot see the current source, volume or state etc. The volume slider does not work. I can adjust the volume with up and down though.

See attached image for how it is shown in HASS.
![soundbar](https://user-images.githubusercontent.com/8121629/105225977-aac52680-5b5f-11eb-9a31-6e75f9e72b44.png)

Any suggestions?

**Comment by PiotrMachowski** [comment]
While waiting for this issue to be fixed you check out a [modified version of SmartThings integration](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings): it adds a support for multimedia devices plus it still works for me.

**Comment by tieppm** [comment]
> While waiting for this issue to be fixed you check out a [modified version of SmartThings integration](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings): it adds a support for multimedia devices plus it still works for me.
hello. this for soundbar Q70r? thank U

**Comment by PiotrMachowski** [comment]
@tieppm 
It should work with all devices supported by this integration (I use it with HW-Q80R)

**Comment by aherbjornsen** [comment]
Thanks for the quick response.
As for the SmartThings integration. I'm a bit unsure about how that is installed. Should I install the standard SmartThings integration first or just the custom_component from here. If the latter, how is it configured in configuration.yaml?

**Comment by PiotrMachowski** [comment]
@aherbjornsen you install it normally (in `custom_components`) - it should work with HACS, then you have to remove existing [built-in SmartThings integration](https://www.home-assistant.io/integrations/smartthings/), restart HA and add it again - custom version replaces built-in version and it can be set up in exactly the same way as "original" one

**Comment by aherbjornsen** [comment]
@PiotrMachowski I'm probably slow (and have no deeper knowledge of this), but the original one does not provide any instructions for manual configuration. Just automated install from "Configuration menu -> Add integration". If I add it that way, will it still use the custom_component?
I have done that, and I can see my soundbar. But the controls does not seem to be different from the (broken) soundbar component.

**Comment by PiotrMachowski** [comment]
@aherbjornsen yes, it will use custom_component.

I use it with Q80R

**Comment by Nathy76** [comment]
@PiotrMachowski 
I've installed the modified version of SmartThings integration. Works fine, but...
same problem: no way to select source.

**Comment by PiotrMachowski** [comment]
It seems that not all devices are affected, my soundbar works fine

**Comment by Nathy76** [comment]
Too bad, especially because it worked a few days ago...

**Comment by am1ter** [comment]
@PiotrMachowski, thank you for your component!
Since last update I have the same issue (no source selection) with my Samsung Soundbar MS650. 
I'll wait for a fix.

**Comment by PiotrMachowski** [comment]
I have to create a script that will collect a data that is needed for me to fix this issue (it is almost ready)

**Comment by PiotrMachowski** [comment]
Can you run [this script](https://pastebin.com/H3tZxJMq) and send me results here or at _piotr.machowski.dev [at] gmail [dot] com_?

**Comment by am1ter** [comment]
@PiotrMachowski thank you for attention.
I have recently sent files with collected data to you by email.

**Comment by PiotrMachowski** [comment]
This issue should be fixed. There seems to be an another problem with **MS650** model, for this purpose I will reopen #7

**Comment by aherbjornsen** [comment]
I just tested this and it is working now. Thanks a lot!
![soundbar2](https://user-images.githubusercontent.com/8121629/106096292-8f48b580-6135-11eb-86fc-053807ca2eac.png)
![soundbar](https://user-images.githubusercontent.com/8121629/106096293-8f48b580-6135-11eb-81cb-243e79eef334.png)
