### ISSUE TITLE
Unable to adjust settings with an automation

### ISSUE THREAD

**Issue by ErikSabel** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#62]
Recently added my soundbar (Samsung Soundbar Q930B)
After updating the configuration file it appears as a device, with has the options to operate and change settings. That part is working, like volume, on and off, play or pause, and sending media to it.
However when trying to add it to an automation, the device is findable. I can only use it as an trigger, but not to adjust something. Would like to increase or decrease the volume as something else happens

**Comment by PiotrMachowski** [comment]
You have to use services instead, e.g.: `media_player.volume_up`

More services here:
https://www.home-assistant.io/integrations/media_player/#media-control-services

**Comment by ErikSabel** [comment]
Tried, but doesn't work

This part is in the yaml code

service: media_player.volume_set
    target:
      device_id: 28a805bbcd0de2a8b2fbf9188d16xxxx
    data:
      volume_level: 0.2

**Comment by PiotrMachowski** [comment]
Use it with entity id

**Comment by ErikSabel** [comment]
Got it! It works when changing to entity id and the id of the entity added
Thanks!

**Comment by ErikSabel** [comment]
Perhaps another question.
Did you manage to change the sound source?
Like if i use this, and turns it on. It is on with the source WIFI. But it has also an input from HDMI eARC. Tried alreay a couple of different words/terms to get the source changed. But didnt manage to get it changed, it gives the error;

Entity
media_player.av_samsung_soundbar_q930b_2 does not support this service

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/issues/44

**Comment by ErikSabel** [comment]
That is about the sound mode. I'm searching for the sound source :)
Sound mode is like surround or stereo or what so ever
Sound source is wifi, hdmi, eARC

**Comment by PiotrMachowski** [comment]
Oh, right. It should be available possible using `media_player.select_source`

**Comment by ErikSabel** [comment]
Yeah correct! That's what I mean
Only it doesn't execute it. If I try it as an entity I got the error message. And as a device it says executed but nothing happens. But I don't know If I use the right words for the source. Any clue how to find those words for the source?

**Comment by PiotrMachowski** [comment]
Available options are in attributes of the media_player entity

**Comment by ErikSabel** [comment]
Yes so in the attributes it should be possible. I found the bellow;

source	no	Name of the source to switch to. Platform dependent.

Now this name of the source is the issue. I don't know how to get the right name
I tried the common names. But also I tried to make an entity card that shows this attribute, however this one is saying unknown - perhaps my code is wrong

type: entity
entity: media_player.av_samsung_soundbar_q930b_2
attribute: source_id

Any clue how to find this?

**Comment by PiotrMachowski** [comment]
[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

Go here and find your entity. All possible sources should be there

**Comment by ErikSabel** [comment]
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/3cf78db8-8bc9-4717-87fa-f1cebf2cf5f6)

 It doesnt say much (at least to me)

If i look into the API.py, I see this row;
CONTROLLABLE_SOURCES = ["bluetooth", "wifi"]
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/4cefe836-5c0f-40bd-b1a6-d2d0f368a061)

So it seems controllable, but so far I didnt manage to sent something to change it

**Comment by PiotrMachowski** [comment]
Do inputs appear when you turn on the soundbar?

**Comment by ErikSabel** [comment]
Yes

Regularly it says TV eARC, as that is my default

When I turn it on via Home assistant it says WIFI, so it changed the source as well instead of only turning it on

**Comment by PiotrMachowski** [comment]
> Do inputs appear when you turn on the soundbar?

I mean in HA

**Comment by ErikSabel** [comment]
I see the following;

When off
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/5c07089e-f7e7-4e7b-978c-67d6303b59a7)

When on
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/405919b6-7dc4-4e36-97fa-2dd76a2a9e9b)

I don't see any inputs

**Comment by PiotrMachowski** [comment]
This entity is not from this integration - it is from [Google Cast](https://www.home-assistant.io/integrations/cast/) integration.

**Comment by ErikSabel** [comment]
I see, you are right! I was mistriggered by that this one appeared when installed the integration

This is the screenshot of the intergration;
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/7b869c4f-61bf-48bb-b713-4a9a034b0ecb)

And these entities;
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/05e2da43-87a0-420a-8c1a-62bc3b91e8d5)

**Comment by ErikSabel** [comment]
Don't ask me how, but I've managed it to get it working!

![Screenshot_20240220-181729](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/assets/154734099/3e024790-e9bc-45b9-b203-74786b4d9e11)

After a lot of attempts it appears

**Comment by PiotrMachowski** [comment]
SmartThings API is sometimes unpredictable :)

**Comment by ErikSabel** [comment]
So it seem
One of the things i did was creating a new api id, so perhaps that was it. But don't know about all the things I tried

**Comment by PiotrMachowski** [comment]
>So it seem
One of the things i did was creating a new api id, so perhaps that was it. But don't know about all the things I tried

Ok, so it was definitely broken on SmartThings side

**Comment by jace** [comment]
I'm having the same problem: my Soundbar's input source is reflected accurately, but I can't change it via `media_player.select_source`. It does nothing. Does it write a log anywhere? HA's logbook doesn't seem to show service call results.

My automation used to work fine, but stopped working some weeks (months?) ago.

```yaml
service: media_player.select_source
data:
  source: HDMI1
target:
  entity_id: media_player.soundbarq990b
```

**Comment by jace** [comment]
Unclear if this is related, but Settings → System → Log shows this:

```python
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:950
First occurred: 2 June 2024 at 23:54:39 (7693 occurrences)
Last logged: 21:15:29

Update for media_player.soundbarq990b fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1295, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 68, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 34, in device_update
    data = resp.json()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jace** [comment]
I just noticed I've been commenting on a closed issue. 🤦
