### ISSUE TITLE
Non string unique_id

### ISSUE THREAD

**Issue by aherbjornsen** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#67]
After upgrading to 1.0.3 and using HA 2024.5.0b4 I see this in the log:

ERROR (MainThread) [homeassistant.helpers.entity_registry] 'media_player' from integration smartthings_soundbar has a non string unique_id '<bound method SmartThingsSoundbarMediaPlayer.unique_id of <entity None=on>>', please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/issues

And also a couple of these:

ERROR (MainThread) [homeassistant.helpers.entity_registry] Unable to serialize entry media_player.soundbar to JSON. Bad data found at $.unique_id=<bound method SmartThingsSoundbarMediaPlayer.unique_id of <entity media_player.soundbar=on>>(<class 'method'>

The integration seems to be working fine though.

**Comment by PiotrMachowski** [comment]
Fixed in `v1.0.4`

**Comment by aherbjornsen** [comment]
You are fast. :-)
Installed 1.0.4 and can confirm that all error messages are gone now.
Thanks again!

**Comment by PiotrMachowski** [comment]
It's either that or 2 years later 😄  it was an easy fix, so I have decided to choose the first approach
