### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by heula** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#75]
For a few months I have my HW N950 soundbar working with this addon in Home Assistant but since a few days it does not work anymore.
All I see is that the soundbar is off while it is not off.

I created a new token but that did not help.
Any idea why it does not work anymore and what a I can do to get it working again?

Thanks.
![2024-10-05 17_38_40-Instellingen – Home Assistant](https://github.com/user-attachments/assets/1b6fdc90-989e-49d9-a37e-aa72e9df884e)

**Comment by heula** [comment]
I see that my soundbar is offline in Smartthings. Diagnotic said that there is no connection with Smartthings Cloud 🤷‍♂️.

**Comment by PiotrMachowski** [comment]
Disconnecting it from the power for a few minutes usually helps with that

**Comment by heula** [comment]
Deleted the soundbar from Smartthings, added it again and now it working again.
