### ISSUE TITLE
DEVICE_CLASS_SPEAKER deprecated, replace with MediaPlayerDeviceClass.SPEAKER

### ISSUE THREAD

**Issue by V4n1X** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#76]
Logger: homeassistant.components.media_player
Quelle: helpers/deprecation.py:197
Integration: Mediaplayer (Dokumentation, Probleme)
Erstmals aufgetreten: 18:16:15 (2 Vorkommnisse)
Zuletzt protokolliert: 18:16:15

DEVICE_CLASS_SPEAKER was used from smartthings_soundbar, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerDeviceClass.SPEAKER instead, please report it to the author of the 'smartthings_soundbar' custom integration

**Comment by PiotrMachowski** [comment]
Fixed in [v1.0.5](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/tree/v1.0.5)
